version: "2"
plugins:
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
  - ".circleci"
  - ".codeclimate.yml"
  - ".github"
  - ".gitignore"
  - ".styleci.yml"
  - "composer.json"
  - "helpers.php"
  - "LICENSE"
  - "phpunit.php"
  - "phpunit.xml"
  - "readme.md"
  - "config/feature-toggle.php"
  - "database/**/*"
  - "src/Contracts/**/*"
  - "src/Facade.php"
  - "src/ServiceProvider.php"
  - "tests/**/*"
  - "vendor/**/*"
